/****************************************************************************************************************************************** 
* Class Name   : INTLAttachmentTriggerService
* Description  : Logic for all INTL Attachment triggers housed here.
* Created By   : Slalom/David Stern 
* Created Date : 17 February 2020
*
* Modification Log:  
* ---------------------------------------------------------------------------------------------------------------------------------------
* Developer                Date               Description 
* ---------------------------------------------------------------------------------------------------------------------------------------
* David Stern(Slalom)     02/17/2020          Created, Logic from all triggers moved to this class.
*****************************************************************************************************************************************/
public class INTLAttachmentTriggerService 
{
    
}