/**
* @ClassName    : SL_AvoidCaseConsumableRecursion 
* @JIRATicket   : LIGHTNI-1812
* @CreatedOn    : 3rd Dec 2019.
* @CreatedBy    : Poonam Dalvi
* @ModifiedBy   : 
* @Description  : Controller to handle the error messages when trying to update the case in order to update the Case Consumable record.
*/
public class SL_AvoidCaseConsumableRecursion 
{
    public static Boolean isCaseUpdate;   
    public static Boolean isBdUpdate=false;
    public static Boolean isCaseProdUpdate=false;
    
    public SL_AvoidCaseConsumableRecursion(){}
}