/*************************************************************************************
* Name          :    ZTS_EU_AddKeyMsgController.
* Description   :    Controller for a New AddKeyMessage.
* Author        :    Ketan
 
Modification Log
----------------
Date             Developer           Comments
---------------------------------------------------------------------------------------
1/23/2014       Ketan            Created

**************************************************************************************/
public with sharing class ZTS_EU_AddKeyMsgController{

//***********************This functionality is not loger being used and as this class. When trying to delete this class, am getting below errorFailed to process the request successfully. Cause(UNKNOWN_EXCEPTION): UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 2041438089-2807 (1905954459)
public void test_method(){
Integer i = 0;	
}

}