/* -----------------------------------------------------------------------------------------------------------------------
Name:        ZTS_EU_SampleLookupOverride_Test.cls
Description: Test Class for ExtensionClass ZTS_EU_SampleLookupOverrideController.cls

Date         Version Author              Summary of Changes 
-----------  ------- -----------------   ------------------------------------------------------------------------------
28-11-2014   1.0     CloudSense(Shefali)   Initial Version    
09-03-2020   1.1     Slalom(Elton Barbosa) Updated Version
03-06-2022   1.2     Ethan @ Zoetis Inc    Removed logic and mark for deletion as this class is no longer in use
------------------------------------------------------------------------------------------------------------------------ */
@isTest
private class ZTS_EU_AccountPositionUtility_Test {
    // TODO: DELETE THIS CLASS
    @isTest
    private static void dummyTest() {
        Test.startTest();
            new ZTS_EU_AccountPositionUtility();
        Test.stopTest();
    }
}