/*******************************************************************************************************************************************
* File Name     :  ZTS_EU_Batch_UpdateAccountPositions
* Description   :  Batch class for updating the field 'Days since last called' on existing Account positions                       

* @author       :   CloudSense (Shreyas)
* Modification Log
===================================================================================================
* Ver.    Date          Author              Modification
---------------------------------------------------------------------------------------------------
* 1.0     18th-Mar-15   Shreyas             Created the class.
* 1.1     3rd-Jun-03    Ethan @ Zoetis Inc  Removed logic, make isTest, and mark for deletion as this class is no longer in use

********************************************************************************************************************************************/
@isTest
global class ZTS_EU_Batch_UpdateAccountPositions {
    // TODO: DELETE THIS CLASS
}