/*************************************************************************************
* Name          :    ZTS_EU_BUG_RecursiveClass
* Description   :    Class to control the recersiveness on Accounts during insert operation
* Author        :    Chandra
 
Modification Log
----------------
Date             Developer             Comments
---------------------------------------------------------------------------------------
 4/10/2014       Chandra            Created

**************************************************************************************/
public class ZTS_EU_BUG_RecursiveClass {

public static boolean isUpdated = True;
public static Set<Id> UpdatedIds= new Set<Id>();

}